### ISSUE TITLE
NetworkError if client has shoddy Internet

### ISSUE THREAD

**Issue by funkytaco** [cliffhall/in-app-pro-shop#11]
**What section of the project is affected?**
- Application

**Describe the bug**

I am seeing a NetworkError occasionally if my Internet is slow.

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://2f2807d6-609f-4b4b-a1d8-8ee3cd281362/inpage.js
Source Map URL: ../sourcemaps/inpage.js.map

**To Reproduce**
1. Go to 'Shops' > Your Shop.
2. Click on Category and Add an Item.
3. Open Web Developer console.

**Expected behavior**
No network timeout.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6 (19G2021)
 - Browser: Firefox 86.0 (64-bit)
 - Version: Demo website
 

**Additional context**

I think my Cloudflare DNS times out and causes this issue.

**Comment by cliffhall** [comment]
> I am seeing a NetworkError occasionally if my Internet is slow.

>```
> Source map error: Error: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://2f2807d6-609f-4b4b-a1d8-8ee3cd281362/inpage.js
> Source Map URL: ../sourcemaps/inpage.js.map
>```

That is a Metamask error, it's not coming from this application. 

This bit...
`moz-extension://2f2807d6-609f-4b4b-a1d8-8ee3cd281362/inpage.js`
...is this: https://metamask.github.io/metamask-extension/inpage.js.html
